services:
  api:
    build: .
    container_name: enterprise-rag-api
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - uploads_data:/app/uploads

  db:
    image: pgvector/pgvector:pg16
    container_name: enterprise-rag-db
    environment:
      POSTGRES_DB: enterprise_rag
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  uploads_data: